### ISSUE TITLE
Crash of handlePublish on linux/386

### ISSUE THREAD

**Issue by phifty** [project-iris/iris-go#20]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x81a2efc]

goroutine 20 [running]:
sync/atomic.AddUint64(0x1883c75c, 0x1, 0x0, 0x1883d170, 0x83f3dd8)
    /opt/go/src/sync/atomic/asm_386.s:118 +0xc
gopkg.in/project-iris/iris-go%2ev1.(_topic).handlePublish(0x1883c750, 0x18995300, 0x36, 0x36)
    /home/philipp/projects/go/src/gopkg.in/project-iris/iris-go.v1/topic.go:78 +0x95
gopkg.in/project-iris/iris-go%2ev1.(_Connection).handlePublish(0x1888a180, 0x189becf0, 0x7, 0x18995300, 0x36, 0x36)
    /home/philipp/projects/go/src/gopkg.in/project-iris/iris-go.v1/events.go:106 +0xbd
created by gopkg.in/project-iris/iris-go%2ev1.(*Connection).procPublish
    /home/philipp/projects/go/src/gopkg.in/project-iris/iris-go.v1/proto.go:468 +0xdd

It seems to be a known problem with go. See https://github.com/golang/go/issues/6404

Best regards

**Comment by phifty** [comment]
I've created a pull request with the fix. #21
